version: '3.8'

services:
  docs-site:
    build: .
    container_name: docs-site
    ports:
      - "5000:5000"
    volumes:
      - ./docs:/app/docs
      - ./site_config.yaml:/app/site_config.yaml
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - docs-network

  # Optional: Add nginx for production
  nginx:
    image: nginx:alpine
    container_name: docs-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - docs-site
    networks:
      - docs-network

networks:
  docs-network:
    driver: bridge
